### ISSUE TITLE
peerDependency error when npm install winston-godot

### ISSUE THREAD

**Issue by darrenqc** [jcrugzz/winston-godot#1]
Hi, I came into some error called peerinvalid when I tried to install winston-godot package. The whole error stack are listed as follows:

2228 verbose stack Error: The package winston does not satisfy its siblings' peerDependencies requirements!
2228 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:125:32
2228 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:267:7
2228 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:138:5
2228 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:251:14
2228 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
2228 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:251:14
2228 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
2228 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:251:14
2228 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
2228 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:251:14

I looked it up in google. I think the problem lies in the conflict between the two versions of winston. In winston-godot, 0.x.x is required while what I have installed and the newest version is 1.0.0. 

So, could you please update the dependency of winston-godot if it's not too much trouble. Thank you.

**Comment by jcrugzz** [comment]
@darrenqc updated and published as `winston-godot@1.0.0`

**Comment by darrenqc** [comment]
@jcrugzz Many thanks. :kissing:
